apiVersion: v1
kind: Pod
metadata:
  name: mc-pod-pass
spec:
  containers:
  - name: nginx-1
    image: nginx
    ports:
    - containerPort: 80
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["3600"]