apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ravi2krishna/login-2436
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  type: LoadBalancer
  selector:
    app: login
  ports:
    - port: 80