# - Comment, k8s will ignore this line

# We can use .yaml or .yml as extensions

# key value
key: value
name: ravi
country: india

# Dictionary - holds a collection of data as a set of key-value pairs. 
dictionary:
  key: value
  key: value
  key: value

person:
  name: ravi
  country: india
  gender: male

# Lists - Multiple Items

list:
- item1
- item2
- item3

courses:
- devops
- aws
- azure

